name: Deploy to production environment
on:
  workflow_call:
    inputs:
      container-tag:
        required: true
        type: string

  workflow_dispatch:
    inputs:
      container-tag:
        description: "Container Tag"
        required: true
        type: string

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_PAT: ${{ secrets.DOCKER_HUB_PAT }}
  DOCKER_CONTAINER: gcstatus-api
  DOCKER_PORT: ${{ secrets.DOCKER_PORT }}
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
  EC2_USERNAME: ec2-user
  EC2_PORT: 22
  DOCKER_TAG: ${{ inputs.container-tag }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USERNAME }}
          key: ${{ env.EC2_SSH_KEY }}
          port: ${{ env.EC2_PORT }}
          envs: DOCKER_CONTAINER, DOCKER_PORT, DOCKER_HUB_USERNAME, DOCKER_HUB_PAT, DOCKER_TAG
          script: |
            echo "Stopping and removing old container, if exists..."
            docker stop $DOCKER_CONTAINER || true
            docker rm $DOCKER_CONTAINER || true

            echo $DOCKER_HUB_PAT | docker login -u $DOCKER_HUB_USERNAME --password-stdin

            echo "Pulling container: $DOCKER_HUB_USERNAME/$DOCKER_CONTAINER:$DOCKER_TAG"
            docker pull $DOCKER_HUB_USERNAME/$DOCKER_CONTAINER:$DOCKER_TAG

            echo "Running the new container..."
            docker run -d --name $DOCKER_CONTAINER -p $DOCKER_PORT:$DOCKER_PORT \
              $DOCKER_HUB_USERNAME/$DOCKER_CONTAINER:$DOCKER_TAG

            echo "Creating .env file inside the container..."
            docker exec $DOCKER_CONTAINER sh -c 'cat <<EOF > /app/.env
              ENV=production
              JWT_TTL=15
              JWT_SECRET=${{ secrets.JWT_SECRET }}
              ACCESS_TOKEN_KEY=${{ secrets.ACCESS_TOKEN_KEY }}
              DB_HOST=${{ secrets.DB_HOST }}
              DB_PORT=${{ secrets.DB_PORT }}
              DB_USER=${{ secrets.DB_USER }}
              DB_PASSWORD=${{ secrets.DB_PASSWORD }}
              DB_NAME=${{ secrets.DB_NAME }}
              IS_AUTH_KEY=${{ secrets.IS_AUTH_KEY }}
              HTTP_SECURE=${{ secrets.HTTP_SECURE }}
              HTTP_ONLY=${{ secrets.HTTP_ONLY }}
              HTTP_DOMAIN=${{ secrets.HTTP_DOMAIN }}
              REDIS_HOST=${{ secrets.REDIS_HOST }}
              PORT=${{ env.DOCKER_PORT }}
              AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}
              AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}
              AWS_MAIL_FROM=${{ secrets.AWS_MAIL_FROM }}
              AWS_MAIL_REGION=${{ secrets.AWS_MAIL_REGION }}
              CORS_DOMAINS=${{ secrets.CORS_DOMAINS }}
              AWS_BUCKET=${{ secrets.AWS_BUCKET }}
              AWS_BUCKET_REGION=${{ secrets.AWS_BUCKET_REGION }}
              AWS_SQS_REGION=${{ secrets.AWS_SQS_REGION }}
              AWS_SQS_URL=${{ secrets.AWS_SQS_URL }}
            EOF'
            echo "Environment variables written successfully."

            echo "Waiting for container to be healthy..."
            until [ "$(docker inspect --format='{{.State.Health.Status}}' $DOCKER_CONTAINER)" == "healthy" ]; do
              echo "Still waiting for container health check to pass..."
              sleep 5
            done
            echo "Container is healthy!"

      - name: Cleanup old Docker containers and images
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USERNAME }}
          key: ${{ env.EC2_SSH_KEY }}
          port: ${{ env.EC2_PORT }}
          script: |
            echo "Stopping and removing all containers except the currently running container..."
            docker ps -aq --filter "name=$DOCKER_CONTAINER" --filter "status=exited" | xargs -r docker rm -f

            echo "Removing unused images to free up space..."
            docker image prune -af || true

            echo "Pruning unused networks and volumes to reclaim space..."
            docker network prune -f || true
            docker volume prune -f || true

            echo "Cleanup complete."
