name: Lint PR title

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  lint-commit-message:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node: [22]
    name: Running lint on pull request title - Node ${{ matrix.node }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Clean packages
        run: |
          rm package.json package-lock.json|| true
          npm init --yes --private

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install Commitlint
        run: npm add --dev commitlint @commitlint/config-conventional

      - name: Run commit message lint on PR title
        run: echo "${{ github.event.pull_request.title }}" | npx commitlint
